In [29]:
import pandas as pd
import numpy as np

# How to create a dataframe from pandas and numpy

In [30]:
#creating from Arrays
test_scores= np.array([[2,3,5,0],[3,5,1,2],[5,6,4,5],[8,9,6,7],[3,5,2,5]])
test_scores

array([[2, 3, 5, 0],
       [3, 5, 1, 2],
       [5, 6, 4, 5],
       [8, 9, 6, 7],
       [3, 5, 2, 5]])

## create a dataframe with pandas and Numpy

In [31]:
show_data= pd.DataFrame(test_scores,)
show_data

   0  1  2  3
0  2  3  5  0
1  3  5  1  2
2  5  6  4  5
3  8  9  6  7
4  3  5  2  5

modify_df= pd.DataFrame(test_scores, index=[0] , columns=[])

In [32]:
modify_df= pd.DataFrame(test_scores, index=['Emeka','victor','helen','chisom','prosper'] ,
                        columns=['maths','phy','chem','bio'])

In [33]:
modify_df

         maths  phy  chem  bio
Emeka        2    3     5    0
victor       3    5     1    2
helen        5    6     4    5
chisom       8    9     6    7
prosper      3    5     2    5

## creating a dataframe without numpy

In [34]:
scores=[[2,3,5,0],[3,5,1,2],[5,6,4,5],[8,9,6,7],[3,5,2,5]]
scores

[[2, 3, 5, 0], [3, 5, 1, 2], [5, 6, 4, 5], [8, 9, 6, 7], [3, 5, 2, 5]]

In [35]:
score_df= pd.DataFrame(scores, index=['Emeka','victor','helen','chisom','prosper'] ,
                        columns=['maths','phy','chem','bio'])

In [36]:
score_df

         maths  phy  chem  bio
Emeka        2    3     5    0
victor       3    5     1    2
helen        5    6     4    5
chisom       8    9     6    7
prosper      3    5     2    5

## Creating a Dataframe from Dictionary

In [11]:
import pandas as pd

In [2]:
subject=['maths','phys', 'chem','bio','Eng']

In [24]:
scores=[89,70,67,78,59]

In [4]:
My_dict= { 'subject':subject, 'Scores':scores}

In [14]:
my_df= pd.DataFrame(My_dict)
my_df

  subject Scores
0   maths     89
1    phys     70
2    chem     67
3     bio     78
4     Eng     59

In [25]:
subject=['maths','phys', 'chem','bio','Eng']
scores=[89,70,67,78,59]
subject.append('TOTAL')
scores.append(sum(scores))

In [26]:
My_dict= { 'subject':subject, 'Scores':scores}
my_df=pd.DataFrame(My_dict)

In [27]:
my_df

  subject  Scores
0   maths      89
1    phys      70
2    chem      67
3     bio      78
4     Eng      59
5   TOTAL     363

## Creating a dataframe from csv file

In [2]:
import os
print(os.getcwd())
print(os.listdir())
import pandas as pd

C:\Users\DELL LATITUDE 5300\Anaconder_script\MODULES_in_python
['.ipynb_checkpoints', 'Pandas_module.ipynb', 'Students_Exam.csv']

In [5]:
# Reading the csv file\
new_df=pd.read_csv('Students_Exam.csv')

In [7]:
new_df.head()

  Names of Students  English  Maths  Economics  Igbo  Agric
0             Ngozi       34     54         75    46     45
1               Ada       53     66         46    77     86
2            victor       76     34         35    86     67
3          Chiemela        3     23         75    54     99
4          Harrison       45     77         56    34     78

In [8]:
new_df

   Names of Students  English  Maths  Economics  Igbo  Agric
0              Ngozi       34     54         75    46     45
1                Ada       53     66         46    77     86
2             victor       76     34         35    86     67
3           Chiemela        3     23         75    54     99
4           Harrison       45     77         56    34     78
5              Henry       23     97         97    67     55
6          Shulamite       66     65         78    88     43
7               Rita       78     53         66    45     54
8             Wilson       99     43         35    76     44
9              Sarah       43     22         74    33     32
10            Youngs       65     34         75    65     35
11           Modesta       68     55         35    45     46
12              John       99     77         45    35     84

## How to display the head and the tail

In [3]:
import pandas as pd
data= pd.read_csv('Students_Exam.csv')
data.head()

  Names of Students  English  Maths  Economics  Igbo  Agric
0             Ngozi       34     54         75    46     45
1               Ada       53     66         46    77     86
2            victor       76     34         35    86     67
3          Chiemela        3     23         75    54     99
4          Harrison       45     77         56    34     78

In [4]:
data.tail()

   Names of Students  English  Maths  Economics  Igbo  Agric
8             Wilson       99     43         35    76     44
9              Sarah       43     22         74    33     32
10            Youngs       65     34         75    65     35
11           Modesta       68     55         35    45     46
12              John       99     77         45    35     84

In [5]:
data.head(8)

  Names of Students  English  Maths  Economics  Igbo  Agric
0             Ngozi       34     54         75    46     45
1               Ada       53     66         46    77     86
2            victor       76     34         35    86     67
3          Chiemela        3     23         75    54     99
4          Harrison       45     77         56    34     78
5             Henry       23     97         97    67     55
6         Shulamite       66     65         78    88     43
7              Rita       78     53         66    45     54

In [6]:
data

   Names of Students  English  Maths  Economics  Igbo  Agric
0              Ngozi       34     54         75    46     45
1                Ada       53     66         46    77     86
2             victor       76     34         35    86     67
3           Chiemela        3     23         75    54     99
4           Harrison       45     77         56    34     78
5              Henry       23     97         97    67     55
6          Shulamite       66     65         78    88     43
7               Rita       78     53         66    45     54
8             Wilson       99     43         35    76     44
9              Sarah       43     22         74    33     32
10            Youngs       65     34         75    65     35
11           Modesta       68     55         35    45     46
12              John       99     77         45    35     84

# Getting access to shape attribute

In [7]:
#getting access to the number of rows and columns present in the given data distribution
data.shape

(13, 6)

In [8]:
#Displaying the data
pd.set_option('display.max_rows',10)
pd.set_option('display.max_columns',4)

In [9]:
data

   Names of Students  English  ...  Igbo  Agric
0              Ngozi       34  ...    46     45
1                Ada       53  ...    77     86
2             victor       76  ...    86     67
3           Chiemela        3  ...    54     99
4           Harrison       45  ...    34     78
..               ...      ...  ...   ...    ...
8             Wilson       99  ...    76     44
9              Sarah       43  ...    33     32
10            Youngs       65  ...    65     35
11           Modesta       68  ...    45     46
12              John       99  ...    35     84

[13 rows x 6 columns]

# Pandas Attributes and Functions

In [10]:
data.shape

(13, 6)

In [11]:
data.index

RangeIndex(start=0, stop=13, step=1)

In [12]:
data.columns

Index(['Names of Students', 'English', 'Maths', 'Economics', 'Igbo', 'Agric'], dtype='str')

In [13]:
data

   Names of Students  English  ...  Igbo  Agric
0              Ngozi       34  ...    46     45
1                Ada       53  ...    77     86
2             victor       76  ...    86     67
3           Chiemela        3  ...    54     99
4           Harrison       45  ...    34     78
..               ...      ...  ...   ...    ...
8             Wilson       99  ...    76     44
9              Sarah       43  ...    33     32
10            Youngs       65  ...    65     35
11           Modesta       68  ...    45     46
12              John       99  ...    35     84

[13 rows x 6 columns]

In [14]:
data.dtypes

Names of Students      str
English              int64
Maths                int64
Economics            int64
Igbo                 int64
Agric                int64
dtype: object

## Methods

In [15]:
#show head()
data.head

<bound method NDFrame.head of    Names of Students  English  ...  Igbo  Agric
0              Ngozi       34  ...    46     45
1                Ada       53  ...    77     86
2             victor       76  ...    86     67
3           Chiemela        3  ...    54     99
4           Harrison       45  ...    34     78
..               ...      ...  ...   ...    ...
8             Wilson       99  ...    76     44
9              Sarah       43  ...    33     32
10            Youngs       65  ...    65     35
11           Modesta       68  ...    45     46
12              John       99  ...    35     84

[13 rows x 6 columns]>

In [16]:
data.head()

  Names of Students  English  ...  Igbo  Agric
0             Ngozi       34  ...    46     45
1               Ada       53  ...    77     86
2            victor       76  ...    86     67
3          Chiemela        3  ...    54     99
4          Harrison       45  ...    34     78

[5 rows x 6 columns]

In [17]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Names of Students  13 non-null     str
 1   English            13 non-null     int64
 2   Maths              13 non-null     int64
 3   Economics          13 non-null     int64
 4   Igbo               13 non-null     int64
 5   Agric              13 non-null     int64
dtypes: int64(5), str(1)
memory usage: 832.0 bytes

In [18]:
data.describe()

         English      Maths  ...       Igbo      Agric
count  13.000000  13.000000  ...  13.000000  13.000000
mean   57.846154  53.846154  ...  57.769231  59.076923
std    28.201200  22.508688  ...  19.845881  21.546313
min     3.000000  22.000000  ...  33.000000  32.000000
25%    43.000000  34.000000  ...  45.000000  44.000000
50%    65.000000  54.000000  ...  54.000000  54.000000
75%    76.000000  66.000000  ...  76.000000  78.000000
max    99.000000  97.000000  ...  88.000000  99.000000

[8 rows x 5 columns]

## Functions

In [19]:
#function
len(data)

13

In [20]:
max(data)

'Names of Students'

In [21]:
max(data.index)

12

In [22]:
min(data.index)

0

In [23]:
min(data)

'Agric'

In [24]:
type(data)

pandas.DataFrame

In [25]:
round(data, 2)

   Names of Students  English  ...  Igbo  Agric
0              Ngozi       34  ...    46     45
1                Ada       53  ...    77     86
2             victor       76  ...    86     67
3           Chiemela        3  ...    54     99
4           Harrison       45  ...    34     78
..               ...      ...  ...   ...    ...
8             Wilson       99  ...    76     44
9              Sarah       43  ...    33     32
10            Youngs       65  ...    65     35
11           Modesta       68  ...    45     46
12              John       99  ...    35     84

[13 rows x 6 columns]

## Selecting a column from a datafram
# 1. Using syntax 1

In [26]:
# Select a Column from a sample of data
data['Names of Students']

0        Ngozi
1          Ada
2       victor
3     Chiemela
4     Harrison
        ...
8       Wilson
9        Sarah
10      Youngs
11     Modesta
12        John
Name: Names of Students, Length: 13, dtype: str

In [28]:
#check the data type
type(data['Names of Students'])

pandas.Series

In [29]:
data['Names of Students'].index

RangeIndex(start=0, stop=13, step=1)

In [30]:
data['Names of Students'].head()

0       Ngozi
1         Ada
2      victor
3    Chiemela
4    Harrison
Name: Names of Students, dtype: str

# Using syntax 2

In [37]:
data['Names of Students']

0        Ngozi
1          Ada
2       victor
3     Chiemela
4     Harrison
        ...
8       Wilson
9        Sarah
10      Youngs
11     Modesta
12        John
Name: Names of Students, Length: 13, dtype: str

## Selecting two or more columns from a dataframe

In [62]:
import pandas as pd
new_df=pd.read_csv('Students_Exam.csv')
new_df

   Names of Students  English  Maths  Economics  Igbo  Agric
0              Ngozi       34     54         75    46     45
1                Ada       53     66         46    77     86
2             victor       76     34         35    86     67
3           Chiemela        3     23         75    54     99
4           Harrison       45     77         56    34     78
5              Henry       23     97         97    67     55
6          Shulamite       66     65         78    88     43
7               Rita       78     53         66    45     54
8             Wilson       99     43         35    76     44
9              Sarah       43     22         74    33     32
10            Youngs       65     34         75    65     35
11           Modesta       68     55         35    45     46
12              John       99     77         45    35     84

In [63]:
pd.set_option('display.max_row', 13)

In [83]:
pd.set_option('display.max_column',10)

In [84]:
new_df

,Names of Students,English,Maths,Economics,Igbo,Agric,Geography,physics
0,Ngozi,34,54,75,46,45,56,55
1,Ada,53,66,46,77,86,34,75
2,victor,76,34,35,86,67,22,61
3,Chiemela,3,23,75,54,99,45,1
4,Harrison,45,77,56,34,78,66,53
5,Henry,23,97,97,67,55,33,52
6,Shulamite,66,65,78,88,43,22,34
7,Rita,78,53,66,45,54,44,29
8,Wilson,99,43,35,76,44,45,19
9,Sarah,43,22,74,33,32,67,18
10,Youngs,65,34,75,65,35,88,10
11,Modesta,68,55,35,45,46,44,28
12,John,99,77,45,35,84,64,83

In [85]:
new_df[['Names of Students', 'Igbo']]

   Names of Students  Igbo
0              Ngozi    46
1                Ada    77
2             victor    86
3           Chiemela    54
4           Harrison    34
5              Henry    67
6          Shulamite    88
7               Rita    45
8             Wilson    76
9              Sarah    33
10            Youngs    65
11           Modesta    45
12              John    35

In [86]:
type(new_df[['Names of Students', 'Igbo']])

pandas.DataFrame

In [87]:
new_df[['Names of Students', 'English', 'Economics','Agric']]

   Names of Students  English  Economics  Agric
0              Ngozi       34         75     45
1                Ada       53         46     86
2             victor       76         35     67
3           Chiemela        3         75     99
4           Harrison       45         56     78
5              Henry       23         97     55
6          Shulamite       66         78     43
7               Rita       78         66     54
8             Wilson       99         35     44
9              Sarah       43         74     32
10            Youngs       65         75     35
11           Modesta       68         35     46
12              John       99         45     84

## Adding New columns in pandas

In [88]:
new_df['Geography']=[56,34,22,45,66,33,22,44,45,67,88,44,64]

In [89]:
new_df

,Names of Students,English,Maths,Economics,Igbo,Agric,Geography,physics
0,Ngozi,34,54,75,46,45,56,55
1,Ada,53,66,46,77,86,34,75
2,victor,76,34,35,86,67,22,61
3,Chiemela,3,23,75,54,99,45,1
4,Harrison,45,77,56,34,78,66,53
5,Henry,23,97,97,67,55,33,52
6,Shulamite,66,65,78,88,43,22,34
7,Rita,78,53,66,45,54,44,29
8,Wilson,99,43,35,76,44,45,19
9,Sarah,43,22,74,33,32,67,18
10,Youngs,65,34,75,65,35,88,10
11,Modesta,68,55,35,45,46,44,28
12,John,99,77,45,35,84,64,83

In [90]:
import numpy as np
physics=np.arange(0,13)

In [91]:
len(physics)

13

In [92]:
# inserting random values between 0-100 for scores in python using random.randint
# np.random.randint(start, end, size=)
physics= np.random.randint(1,100, size=13)
physics

array([ 3,  6, 89, 77, 78, 22, 58, 16,  3, 39, 78, 34,  9], dtype=int32)

In [93]:
len(physics)

13

In [94]:
new_df['physics'] = physics

In [95]:
new_df

,Names of Students,English,Maths,Economics,Igbo,Agric,Geography,physics
0,Ngozi,34,54,75,46,45,56,3
1,Ada,53,66,46,77,86,34,6
2,victor,76,34,35,86,67,22,89
3,Chiemela,3,23,75,54,99,45,77
4,Harrison,45,77,56,34,78,66,78
5,Henry,23,97,97,67,55,33,22
6,Shulamite,66,65,78,88,43,22,58
7,Rita,78,53,66,45,54,44,16
8,Wilson,99,43,35,76,44,45,3
9,Sarah,43,22,74,33,32,67,39
10,Youngs,65,34,75,65,35,88,78
11,Modesta,68,55,35,45,46,44,34
12,John,99,77,45,35,84,64,9

In [97]:
chemistry= np.random.randint(1.0, 100.0, size=13)
chemistry

array([85, 14, 51, 60,  7, 76, 82, 48, 16, 91, 70, 56, 78], dtype=int32)

In [98]:
new_df['Chemistry']=chemistry

In [99]:
new_df

,Names of Students,English,Maths,Economics,Igbo,Agric,Geography,physics,Chemistry
0,Ngozi,34,54,75,46,45,56,3,85
1,Ada,53,66,46,77,86,34,6,14
2,victor,76,34,35,86,67,22,89,51
3,Chiemela,3,23,75,54,99,45,77,60
4,Harrison,45,77,56,34,78,66,78,7
5,Henry,23,97,97,67,55,33,22,76
6,Shulamite,66,65,78,88,43,22,58,82
7,Rita,78,53,66,45,54,44,16,48
8,Wilson,99,43,35,76,44,45,3,16
9,Sarah,43,22,74,33,32,67,39,91
10,Youngs,65,34,75,65,35,88,78,70
11,Modesta,68,55,35,45,46,44,34,56
12,John,99,77,45,35,84,64,9,78

In [100]:
min(physics)

np.int32(3)

In [101]:
max(physics)

np.int32(89)

# How to create random float numbers

In [102]:
np.random.uniform(1,100, size=13)

array([82.58644491, 70.8486196 ,  6.24031028, 35.94133002, 78.63581727,
       64.1884797 , 74.95781466, 31.56678366, 12.32488988, 63.38701318,
       17.22739449, 80.38369966, 83.78418503])

In [105]:
Biology_Average=np.random.uniform(1,100, size=13)
Biology_Average

array([55.80568314, 98.36950595, 70.27999661, 14.65092993, 54.25410752,
       13.01460027, 60.4336246 , 30.65061077, 90.07790267, 45.83857838,
       45.86197081,  1.578008  ,  8.10692386])

In [106]:
new_df['Biology (first,second and third term Average)']=Biology_Average

In [107]:
new_df

,Names of Students,English,Maths,Economics,Igbo,Agric,Geography,physics,Chemistry,"Biology (first,second and third term Average)"
0,Ngozi,34,54,75,46,45,56,3,85,55.805683
1,Ada,53,66,46,77,86,34,6,14,98.369506
2,victor,76,34,35,86,67,22,89,51,70.279997
3,Chiemela,3,23,75,54,99,45,77,60,14.650930
4,Harrison,45,77,56,34,78,66,78,7,54.254108
5,Henry,23,97,97,67,55,33,22,76,13.014600
6,Shulamite,66,65,78,88,43,22,58,82,60.433625
7,Rita,78,53,66,45,54,44,16,48,30.650611
8,Wilson,99,43,35,76,44,45,3,16,90.077903
9,Sarah,43,22,74,33,32,67,39,91,45.838578
10,Youngs,65,34,75,65,35,88,78,70,45.861971
11,Modesta,68,55,35,45,46,44,34,56,1.578008
12,John,99,77,45,35,84,64,9,78,8.106924

# 1. Adding a new column with assign() and Insert()
## 1.1 assign()
### when to use assign()
     Add multiple column in a single line of code
    When you need to overwrite the value of an existing column in practice